"""Add can_create_events and can_create_users columns

Revision ID: ffb506736d17
Revises: 
Create Date: 2025-08-10 13:16:22.664470

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ffb506736d17'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('can_create_events', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('can_create_users', sa.Boolean(), nullable=True))
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_column('users', 'can_create_users')
    op.drop_column('users', 'can_create_events')
    # ### end Alembic commands ###
